---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by paradox
--- DateTime: 2025/10/3 16:18
--- KEYS[1]是锁的key ARGV[1]当前线程标识
--获取锁中的线程标识 get key
local key = KEYS[1]
-- 线程标识
local threadId = ARGV[1]
--比较线程
local id = redis.call('get',key)
if(id == threadId) then
    return redis.call('del',key)
end
return 0